title: Hieu Do
url: "https://hieuddo.github.io/"
# baseurl: "/hieuddo.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-193328703-1

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Resume"
   link: "resume.pdf"

links:
  - name: "AI Conference Deadlines"
    link: "https://aideadlin.es/"
  - name: "WikiCFP"
    link: "http://www.wikicfp.com/cfp/"
  - name: "DBWorld"
    link: "https://research.cs.wisc.edu/dbworld/browse.html"
  - name: "Upcoming CS Conferences"
    link: "http://www.conferencelist.info/upcoming.html"
  - name: "Ranking"
    link: "http://www.conferencelist.info/targets.html"